#!/usr/bin/env bash
# Auth: kelechi nnadi <alx swe>
# Write a Bash script that displays a list of currently running processes

echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"

ps -e -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,cmd --forest | tail -n +2

