#!/usr/bin/env bash
# Write a Bash script that loops from 1 to 10 and

a=1
while (( $a <= 8 ));
do
	if [ $a == 4 ];
	then
		echo "bad luck";
	elif [ $a == 7 ];
	then
		echo "good luck";
	fi
	echo "Best School";
	((a++))
done;
